### ISSUE TITLE
Admin menu icon is missing

### ISSUE THREAD

**Issue by lkallas** [sendsmaily/sendsmaily-wordpress-plugin#1]
WP admin dashboard menu icon is missing for sendsmaily plugin when the plugin is downloaded via wordpress dashboard.

In github the icon.png exists.

**Comment by kaittodesk** [comment]
Hello, @lkallas!

Thank you for reporting the issue! And sorry for a late reply :)
We have updated the plugin and a new version should be available in your Wordpress installation.

Has it fixed the missing icon issue for you?

**Comment by lkallas** [comment]
Hi!

Yes the issue has been fixed! Closing.
