### ISSUE TITLE
Plugin v 3.1.1 notices and warnings on WordPress v 6.3.1

### ISSUE THREAD

**Issue by merilins** [sendsmaily/sendsmaily-wordpress-plugin#136]
**Bug description**
Updating Smaily plugin from version 3.0.7 to version 3.1.1 throws multiple notices and errors on WordPress version 6.3.1.

**Steps for reproducing**
1. Start with Wordpress v 6.2 and Smaily v 3.0.7
2. Update WP version to 6.3.1
3. Update Smaily version to 3.1.1

**Expected behavior**
Smaily plugin updates to latest version without any notices/errors

**Actual behavior**
Multiple errors and notices thrown after update.

**Errors:**
Notice: Function wp_register_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the smaily-for-wp-newsletter-subscription-block-editor-script handle.
Notice: Function wp_style_is was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the smaily-for-wp-newsletter-subscription-block-editor-style handle. 
Notice: Function wp_register_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the smaily-for-wp-newsletter-subscription-block-editor-style handle. 
Notice: Function wp_style_is was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the smaily-for-wp-newsletter-subscription-block-style handle.
Notice: Function wp_register_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the smaily-for-wp-newsletter-subscription-block-style handle.
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5905) in /var/www/html/wp-admin/includes/misc.php on line 1431
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5905) in /var/www/html/wp-includes/functions.php on line 6935
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5905) in /var/www/html/wp-admin/admin-header.php on line 9

**Screenshots**
![image](https://github.com/sendsmaily/sendsmaily-wordpress-plugin/assets/37170506/a144621f-104a-46f8-b0c2-f24f139776c4)

**Plugin version:**
3.1.1

**Wordpress version:**
6.3.1

**PHP version:**
8.0.30

**Comment by kaittodesk** [comment]
Thank you for reporting the issue!

This has been rectified by PR #139 and released in version 3.1.2.
