### ISSUE TITLE
Error message when activating plugin

### ISSUE THREAD

**Issue by sinukaarel** [sendsmaily/sendsmaily-wordpress-plugin#14]
## Description

When activating plugin wordpress sends you error message:

![image](https://user-images.githubusercontent.com/22918359/58877000-53e3b280-86d8-11e9-8a88-ea07edd5c6a1.png)

Headers allready sent. Everything else works but you see an error message when activating plugin.

## Versions

WP : 5.2.1
Server : MySQL v. 5.7.26-0ubuntu0.18.04.1 - (Ubuntu)
Plugin :  1.2.1 

## Reproduce

1. Download plugin from Wordpress repo
2. Press activate
3. Error appears

## Error log generated by WordPress

Seems to be connected with broken SQL when installing tables.

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`wp_sendsmaily_config`' at line 1 päringule SHOW TABLES LIKE `wp_sendsmaily_config`, mille esitas activate_plugin, do_action('activate_sendsmaily-wordpress-plugin/sendsmaily.php'), WP_Hook->do_action, WP_Hook->apply_filters, sendsmaily_install

-----

WordPressi andmebaasiviga Table 'wp_sendsmaily_config' already exists päringule CREATE TABLE `wp_sendsmaily_config` (
			`key` VARCHAR(128) NOT NULL,
			`domain` VARCHAR(255) NOT NULL,
			`autoresponder` INT(16) NOT NULL,
			`form` TEXT NOT NULL,
			`is_advanced` TINYINT(1) NOT NULL,
			PRIMARY KEY(`key`)
		) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;, mille esitas activate_plugin, do_action('activate_sendsmaily-wordpress-plugin/sendsmaily.php'), WP_Hook->do_action, WP_Hook->apply_filters, sendsmaily_installx

---

WordPressi andmebaasiviga You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`wp_sendsmaily_autoresp`' at line 1 päringule SHOW TABLES LIKE `wp_sendsmaily_autoresp`, mille esitas activate_plugin, do_action('activate_sendsmaily-wordpress-plugin/sendsmaily.php'), WP_Hook->do_action, WP_Hook->apply_filters, sendsmaily_install

---

WordPressi andmebaasiviga Table 'wp_sendsmaily_autoresp' already exists päringule CREATE TABLE `wp_sendsmaily_autoresp` ( `id` INT(16) NOT NULL, `title` VARCHAR(255) NOT NULL, PRIMARY KEY (`id`) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;, mille esitas activate_plugin, do_action('activate_sendsmaily-wordpress-plugin/sendsmaily.php'), WP_Hook->do_action, WP_Hook->apply_filters, sendsmaily_install

**Comment by sinukaarel** [comment]
When converting to use `dbDelta()` function for creating and managing table structure there is a problem with column name.
```
	// Create database table - settings.
	$table_name    = $wpdb->prefix . 'sendsmaily_config';
	$smaily_config = "CREATE TABLE $table_name (
						key varchar(128) NOT NULL,
						domain varchar(255) NOT NULL,
						autoresponder int(16) NOT NULL,
						form text NOT NULL,
						is_advanced tinyint(1) NOT NULL,
						PRIMARY KEY  (key)
						) $charset_collate;";
	dbDelta( $smaily_config );
```

`key` is considered as sql keyword and wont be used as column name.

**Comment by kaittodesk** [comment]
Column names can be wrapped with backticks (assuming that MySQL is configured in such way) to avoid conflicts with SQL keywords. Perhaps Wordpress has a method for wrapping column names that takes into account server configuration (something similar to `esc_sql`)?

**Comment by sinukaarel** [comment]
The `dbDelta()` function states that [You must not use any apostrophes or backticks around field names](https://codex.wordpress.org/Creating_Tables_with_Plugins#Creating_or_Updating_the_Table). That's why the `key` column is considered an SQL keyword and you cant use any reserved names.

Note that the dbDelta function is rather picky, but can be very handy for updates.

**Comment by kaittodesk** [comment]
Oh. I did not know that. Thanks you for the information.

Then we are in a sticky situation. We would need to change the table schema without breaking any of the existing installations - a rather impossible task.

Using database table version tracking and `dbDelta` to upgrade the table is not possible, because the initial table with invalid column name would still be needed before upgrade can be applied.

Options I see, are:
1. Write custom peace of code that checks if `key` column exists in the table on each page request(?) and run the column upgrade when necessary. Through it would also mean that both `key` and (for example) `api_key` columns need to be supported by the plugin;
2. Go for version 2.0 of the plugin which has the correct column name from the beginning, and push for users to upgrade.
