### ISSUE TITLE
Should switch database schema to use dbDelta for table creation

### ISSUE THREAD

**Issue by sinukaarel** [sendsmaily/sendsmaily-wordpress-plugin#18]
The current `wp_sendsmaily_config` table is created with pure SQL statement manipulating DB.

It would be better to use `dbDelta()` functionality to simplify further updates.

Switching to `dbDelta()` functionality requires to make major update - need to change DB schema.
Should change `key` column name to something different because with `dbDelta()` functionality you can't use backtick around field names (**key** is reserved statement in SQL syntax and requires backticks). [More info about the `dbDelta()`](https://codex.wordpress.org/Creating_Tables_with_Plugins#Creating_or_Updating_the_Table)

More info can be found also from previous pull-request https://github.com/sendsmaily/sendsmaily-wordpress-plugin/pull/17#issuecomment-526554540 where this issue was postponed due to breaking change.

**Comment by kaittodesk** [comment]
I think the best path to take would be:
1) create a completely new Wordpress plugin, with separate Git repository (would have to come up with a good name);
2) release new plugin with database table column fix;
3) release version 1.2.x of the current plugin with implemented uninstallation hooks;
3) release version 1.x of current plugin and add deprecation notice to it and point the old plugin to the new plugin;

**Comment by kaittodesk** [comment]
Not sure if we need to have separate Git repository. Maybe rename this one to `smaily-wordpress-plugin` and just create a version 2.0 release? And we could just release 2.0 under the new Wordpress plugin.
