### ISSUE TITLE
Nonce verification lasts 24 hours

### ISSUE THREAD

**Issue by sinukaarel** [sendsmaily/sendsmaily-wordpress-plugin#36]
I was working with a store that uses plugin generated form to integrate Icegram popup functionality.

So I found out that the nonce [verification lasts 24 hours](https://developer.wordpress.org/reference/functions/wp_verify_nonce/#description) and after that, it is considered invalid.

So the nonce verification is redundant:
https://github.com/sendsmaily/sendsmaily-wordpress-plugin/blob/c616bb555b7db1c95a2d917e5bc971fec9c6612a/sendsmaily.php#L175-L179

I think the only solution is to remove that because the other form (widget generated one) does not validate it either. And I think it can't be used like that. It should be dynamic and generated each time form is built. Also mentioned in #32

**Comment by kaittodesk** [comment]
With version 2.0 we have reworked how the subscriber opt-in form works in the plugin. Nonce field has been removed and form submits its data directly to Smaily (to utilize the CAPTCHA confirmation provided by `/api/opt-in/` endpoint).

I am not sure though how the new implmentation will behave with Icegram popup.

**Comment by sinukaarel** [comment]
Ok, I see that there is a 2.0 version in progress.
Also, the `/api/opt-in/` endpoint works with Icegram, just tested.

**Comment by kaittodesk** [comment]
2.0 has been released. Plugin is available in Wordpress.org plugins directory - https://wordpress.org/plugins/smaily-for-wp/

**Comment by kaittodesk** [comment]
@sinukaarel is this issue still relevant. If not, please close it.

**Comment by sinukaarel** [comment]
Closing as it's no longer relevant
