### ISSUE TITLE
Smaily form class attribute

### ISSUE THREAD

**Issue by lkallas** [sendsmaily/sendsmaily-wordpress-plugin#4]
Smaily form has ID. Some developers may want to use smaily form in different parts of the page. For example in the page footer and on "news" page header. 

Therefore it would be wise if the form has class attribute as well. So that the submit action is handled in `sendsmaily-wordpress-plugin/js/default.js`

Right now it is possible to have only one smaily form per page without modifying plugin source.

**Comment by TomAbel** [comment]
Since the 2.0 release, form submits aren't handled by JavaScript anymore. It is an HTML form element which posts to subdomain.sendsmaily.net. Multiple forms can be used per page without modifying source code.
