### ISSUE TITLE
Add plugin version to API requests User-Agent header

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#46]
It would be great if we could include current installed plugin version in HTTP requests made against Smaily API. Plugin could utilize HTTP User-Agent header for that.

This could provide us with valuable information about versions active installations use.

For example, current Wordpress User-Agent header is something like:
> WordPress/5.4.1; https://www.example.com

After adding our plugin name and version it could look something like:
> WordPress/5.4.1; https://www.example.com; smaily-for-wp/2.0.1

It would be as simple as applying a filter to `http_headers_useragent`.

**Comment by TomAbel** [comment]
I tried applying the filter but Chrome Dev tools still shows it as Mozilla/5.0. I'm guessing the filter actually worked, but Chrome always shows my user agent. Any way to see the modified header or what am I doing wrong?
The filter would affect all HTTP requests, right? Why not specify user-agent as an argument in `wp_remote_get`

**Comment by kaittodesk** [comment]
User-Agent header is typically provided by the one who is making the request. If you look at the header in Chorme Dev Tools, then it is always the value that Chrome provides (it can be changed, but then you are only changing it for this Chrome installation).

`http_header_useragent` changes the User-Agent header value for requests made from Wordpress. These requests aren't visible to your browser and thus you cannot see the change in User-Agent header.

> The filter would affect all HTTP requests, right? Why not specify user-agent as an argument in `wp_remote_get`.

Thanks for pointing it out. Overriding User-Agent header globally isn't such a good idea, because it might affect the User-Agent header for 3rd party plugins. Providing the User-Agent value through `wp_remote_get` is a better approach. Though it should still include the default User-Agent header information, and have our plugin information appended to it.
