### ISSUE TITLE
Improve API credentials verification form

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#48]
Current form can be confusing to the user. And there are a couple of things we can do to improve its usability:
- Add link to API user creation guide - http://help.smaily.com/en/support/solutions/articles/16000062943-create-api-user;
- Rename "Username" and "Password to "API username" and "API password" respectively;

**Comment by TomAbel** [comment]
Closed with #55 and implemented in 2.2.0.
