### ISSUE TITLE
Rework plugin directory structure

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#68]
Current directory structure lacks... structure.

Most notable problems:
- static files are scattered into multiple directories;
- plugin lifecycle hooks (activation, uninstall) are in multiple files and directories;

I suggest making following changes to rework the directory structure:
- create a new directory called `inc` to house all of the local classes;
- move files in `code` to `inc`;
- move `includes/subscriber-widget.php` to `inc`;
- move `smaily_install` hook to `smaily-for-wp.php`, and delete `includes/activator.php`;
- rework the uninstall.php file to a hook inside `smaily-for-wp.php` file.

These changes will most likely require a major release.

EDIT: renamed `lib` directory to `inc`.

**Comment by kaittodesk** [comment]
Another alternative would be to move towards https://github.com/DevinVinson/WordPress-Plugin-Boilerplate, like we are using it for our Contact Form 7 plugin.

**Comment by TomAbel** [comment]
> Another alternative would be to move towards https://github.com/DevinVinson/WordPress-Plugin-Boilerplate, like we are using it for our Contact Form 7 plugin.

I enjoyed using that as a boilerplate, especially separating the admin/public code.

**Comment by TomAbel** [comment]
Closing as this as the upcoming 3.0.0 release has changed the directory structure.
