### ISSUE TITLE
Move autoresponder from settings page to widget

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#71]
**Is your feature request related to a problem? Please describe.**
Autoresponder of the opt-in form can only be set globally from plugin settings, which essentially limits the number of forms user can setup using the widgets and which automations they trigger. An alternative for the user is to use HTML widgets, but this can be overwhelming for some users who are not familiar with HTML and Smaily API.

**Describe the solution you'd like**
I suggest we move autoresponder selection to opt-in form widget, to improve flexibility of the widget.

**Comment by TomAbel** [comment]
Should we leave a note of where autoresponders can be configured for a few releases? 
In place of autoresponder `select`, a text like: "Autoresponders can be configured in widget settings!"

**Comment by kaittodesk** [comment]
I think there is no need for that. An upgrade notice to let the user know should suffice.

**Comment by TomAbel** [comment]
Autoresponders are available to configure in widget settings as of 3.0.0
