### ISSUE TITLE
Clean up localization files usage

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#72]
**Replace English PO/MO files with POT file**
Wordpress recommends using POT file as the template for translation files - https://developer.wordpress.org/apis/handbook/internationalization/localization/#pot-portable-object-template-files. The file should contain original strings in English.

This renders English PO/MO files mute and they can be removed.

**Remove language files with country code**
Wordpress requires translation files to be named by pattern `my-plugin-{locale}.mo`. This would mean that `wp_smaily-et.mo` and `wp_smaily-en.mo` are not being used and can be removed.

**Comment by TomAbel** [comment]
merged into 2.3.0
