### ISSUE TITLE
Settings page tab are broken

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#74]
**Bug description**
Settings page tabs are out of alignment, and in some cases completely broken, depending on activated plugins.

**Steps for reproducing**

1. Go to your site admin panel.
2. Install and activate both WPML and Smaily for WP plugin.
3. Go to Smaily for WP settings.

**Expected behavior**
Expected to see all tab on the same horizontal line.

**Actual behavior**
First tab is higher than the rest.

**Screenshots**
WPML deactivated:
![2020-11-30_13h27_40-001](https://user-images.githubusercontent.com/6755852/100766586-79eb2f80-3401-11eb-98c5-43d17c01655f.png)

WPML activated:
![2020-11-30_13h27_40-002](https://user-images.githubusercontent.com/6755852/100766608-7eafe380-3401-11eb-973f-89d2f98a0d43.png)

**Versions**
WordPress: 5.5.3
Smaily for WP: 2.2.1
WPML: 4.4.3

**Comment by TomAbel** [comment]
this looks like an issue with the woocommerce plugin

**Comment by kaittodesk** [comment]
Yeah, you are right. For some reason I thought the issue is also present in Smaily for WP plugin, but it does not have such tab functionality. Closing issue.
