### ISSUE TITLE
Better plugin upgrade logic

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#76]
**Is your feature request related to a problem? Please describe.**
It is really tedious to deactivate and activate plugin everytime plugin updated to make sure every database change gets applied.

**Describe the solution you'd like**
I am not sure what the exact technical solution should be, but it would provide a better use experience if database changes could get automatically applied when plugin upgrade happens.

**Comment by TomAbel** [comment]
Closing, 3.0.0 will have improved upgrade logic.
