### ISSUE TITLE
User-Agent string format

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/sendsmaily-wordpress-plugin#81]
Current User-Agent string does not follow common practices of User-Agent strings used by libraries and web browsers:

> WordPress/5.5.1; https://example.com; smaily-for-wp/2.3.0

The common practice is to provide the plugin's name and version as the first item and rest of the metadata in parenthesis following the name and version. For example:

> smaily-for-wp/2.3.0 (WordPress/5.5.1; +https://example.com)

I recommend we update the format of the User-Agent string in the plugin to latter example.

**Comment by TomAbel** [comment]
Implemented, available in 3.0.0
